// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANJYVziOLDNOQkiObKQLW9CiDurbTlR3o',
    appId: '1:220024621102:web:69014f92a27a955077f7bf',
    messagingSenderId: '220024621102',
    projectId: 'livraison-4168f',
    authDomain: 'livraison-4168f.firebaseapp.com',
    storageBucket: 'livraison-4168f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARf6me02Hhy5MyjNZlsfRdbT2AbSpkZro',
    appId: '1:220024621102:android:1fe8331114ed162e77f7bf',
    messagingSenderId: '220024621102',
    projectId: 'livraison-4168f',
    storageBucket: 'livraison-4168f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSpv7LT3LaWLQsew2b8aLsDbgAmtcDE8Q',
    appId: '1:220024621102:ios:aceb701b103eb2de77f7bf',
    messagingSenderId: '220024621102',
    projectId: 'livraison-4168f',
    storageBucket: 'livraison-4168f.appspot.com',
    iosClientId: '220024621102-596qum5ne748s7bj7rnrgiln4ddomall.apps.googleusercontent.com',
    iosBundleId: 'com.example.food',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSpv7LT3LaWLQsew2b8aLsDbgAmtcDE8Q',
    appId: '1:220024621102:ios:b78ec5ddb85cace977f7bf',
    messagingSenderId: '220024621102',
    projectId: 'livraison-4168f',
    storageBucket: 'livraison-4168f.appspot.com',
    iosClientId: '220024621102-la4f8btbhv6sgqgm2agnrs8gojqsqqcp.apps.googleusercontent.com',
    iosBundleId: 'com.example.food.RunnerTests',
  );
}
